config/routes.rb
Rails.application.routes.draw do
  get 'game', to:'referee#game'

  get 'score', to:'referee#score'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/referee_controller.rb
require 'open-uri'
require 'json'

class RefereeController < ApplicationController
  def game
    @newgrid = Array.new(9) { ('A'..'Z').to_a[rand(26)] }
    @start_time = Time.now
  end

  def score
    @attempt = params[:attempt]
    @grid = params[:grid].split("")
    @start_time = params[:start_time].to_time
    @end_time = Time.now
    # @time_taken = @end_time - @start_time
    @result = run_game(@attempt, @grid, @start_time, @end_time)
  end

  def included?(guess, grid)
    guess.split("").all? { |letter| guess.count(letter) <= grid.count(letter) }
  end

  def compute_score(attempt, time_taken)
    (time_taken > 60.0) ? 0 : attempt.size * (1.0 - time_taken / 60.0)
  end

  def run_game(attempt, grid, start_time, end_time)
    result = { time: end_time - start_time }

    result[:translation] = get_translation(attempt)
    result[:score], result[:message] = score_and_message(
      attempt, result[:translation], grid, result[:time])

    result
  end

  def score_and_message(attempt, translation, grid, time)
    if included?(attempt.upcase, grid)
      if translation
        score = compute_score(attempt, time)
        [score, "well done"]
      else
        [0, "not an english word"]
      end
    else
      [0, "not in the grid"]
    end
  end

  def get_translation(word)
    api_key = "YOUR_SYSTRAN_API_KEY"
    begin
      response = open("https://api-platform.systran.net/translation/text/translate?source=en&target=fr&key=#{api_key}&input=#{word}")
      json = JSON.parse(response.read.to_s)
      if json['outputs'] && json['outputs'][0] && json['outputs'][0]['output'] && json['outputs'][0]['output'] != word
        return json['outputs'][0]['output']
      end
    rescue
      if File.read('/usr/share/dict/words').upcase.split("\n").include? word.upcase
        return word
      else
        return nil
      end
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/referee_helper.rb
module RefereeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsLongestWordGame</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/referee/game.html.erb
<h1>Referee#game</h1>
<p>Find me in app/views/referee/game.html.erb</p>

<p><%= @newgrid.join(" ") %></p>


<form action="<%= score_path %>" method="GET">
  <label for="question">What is your attempt?</label>
  <input type="text" name="attempt" placeholder="Size">
  <input type="hidden" name="grid" value="<%= @newgrid.join("") %>">

  <input type="hidden" name="start_time" value="<%= Time.now %>">

  <input type="submit" value="Go on!">
</form>

app/views/referee/score.html.erb
<h1>Referee#score</h1>
<p>Find me in app/views/referee/score.html.erb</p>

<p>Your try: <%= @attempt %></p>

<!-- <p>You took <%= @time_taken %> seconds</p> -->

<p>Your score is <%= @result %></p>